spring.datasource.url=${consultation_db}
spring.datasource.username=${consultation_db_user}
spring.datasource.password=${1qgLE6OvXDv8og73lkpO8I6Gfs3W9Udp}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}