spring.datasource.url=jdbc:postgresql://localhost:5432/consultation_db
spring.datasource.username=postgres
spring.datasource.password=Garvish@2908

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ConsultHubSecretKeyForJwtTokenGeneration2026SecureKey!!
jwt.expiration-ms=86400000